import { Testimonial } from "@/types";

export const TESTIMONIALS: Testimonial[] = [
  {
    name: "Priya Ramachandran",
    avatar: "PR",
    avatarBg: "linear-gradient(135deg, #FF6B6B, #FF8E53)",
    year: "2025",
    text: "I struggled with Speaking fluency and pronunciation. The structured practice sessions and real examiner feedback helped me improve from Band 6 to 7.5. I learned techniques to expand answers naturally and handle Part 3 confidently.",
    highlight: "Band 6 → 7.5 in Speaking",
    rating: 5,
    course: "IELTS Speaking Mastery",
  },
  {
    name: "Arjun Krishnamurthy",
    avatar: "AK",
    avatarBg: "linear-gradient(135deg, #667EEA, #764BA2)",
    year: "2024",
    text: "Listening was my weakest module. The note-taking strategies and focus techniques helped me catch details I used to miss. Went from Band 6.5 to 8.0 by practicing with real exam patterns.",
    highlight: "Band 6.5 → 8.0 in Listening",
    rating: 5,
    course: "IELTS Listening Excellence",
  },
  {
    name: "Sneha Murugan",
    avatar: "SM",
    avatarBg: "linear-gradient(135deg, #11998E, #38EF7D)",
    year: "2025",
    text: "Reading comprehension was eating up too much time. Learning skimming, scanning, and keyword matching techniques helped me manage time better and achieve Band 8.5 in Reading.",
    highlight: "Achieved Band 8.5 in Reading",
    rating: 5,
    course: "IELTS Reading Strategy",
  },
  {
    name: "Rahul Venkatesh",
    avatar: "RV",
    avatarBg: "linear-gradient(135deg, #F093FB, #F5576C)",
    year: "2024",
    text: "I was stuck at Band 6 in Writing for months. The structure training for Task 1 & 2, idea planning, and examiner-focused tips helped me improve to Band 7.5. Finally understood what examiners actually look for.",
    highlight: "Band 6 → 7.5 in Writing",
    rating: 5,
    course: "IELTS Writing (Task 1 & 2)",
  },
  {
    name: "Harini Subramanian",
    avatar: "HS",
    avatarBg: "linear-gradient(135deg, #4FACFE, #00F2FE)",
    year: "2025",
    text: "The Speaking mock tests with instant feedback were game-changers. I learned how to organize my thoughts quickly and speak with confidence. Achieved Band 8 in my first attempt!",
    highlight: "Band 8 in first attempt",
    rating: 5,
    course: "IELTS Speaking Confidence",
  },
  {
    name: "Karthik Sundaram",
    avatar: "KS",
    avatarBg: "linear-gradient(135deg, #FA709A, #FEE140)",
    year: "2024",
    text: "Listening accents were my biggest challenge. The training exposed me to British, Australian, and American accents systematically. My comprehension improved dramatically, scoring Band 8.5.",
    highlight: "Mastered multiple accents",
    rating: 5,
    course: "IELTS Listening Accents",
  },
  {
    name: "Divya Prakash",
    avatar: "DP",
    avatarBg: "linear-gradient(135deg, #FD297B, #FF655B)",
    year: "2025",
    text: "Reading True/False/Not Given questions always confused me. The logical approach and elimination techniques I learned helped me achieve 38/40 in Reading. Highly recommend!",
    highlight: "38/40 in Reading Module",
    rating: 5,
    course: "IELTS Reading Accuracy",
  },
  {
    name: "Vikram Patel",
    avatar: "VP",
    avatarBg: "linear-gradient(135deg, #89F7FE, #66A6FF)",
    year: "2024",
    text: "Writing Task 2 essays under time pressure was stressful. I learned planning techniques, powerful vocabulary, and clear paragraph structures. Scored Band 7.5 in Writing after three failed attempts.",
    highlight: "Band 7.5 after 3 attempts",
    rating: 5,
    course: "IELTS Writing Task 2 Mastery",
  },
  {
    name: "Anjali Menon",
    avatar: "AM",
    avatarBg: "linear-gradient(135deg, #A8EDEA, #FED6E3)",
    year: "2025",
    text: "Speaking Part 2 (cue card) terrified me. The STAR technique and topic-specific vocabulary training helped me structure 2-minute answers confidently. Got Band 7.5 in Speaking!",
    highlight: "Conquered cue card fear",
    rating: 5,
    course: "IELTS Speaking Part 2",
  },
];
